### PR TITLE
Deconvolve

### PR DESCRIPTION
**Pull request by alexberndt**
I replaced the code in the virtual reference function to use scipy.signal.lfilter instead of the manual de-convolution. 

It goes without saying that I ensured that all unittests were passed, and examples work.

Note that in test_reference.py, I removed the leading 0 from the numerator in line 66. It is now 'num = [1-1.6+0.63]' instead of the original 'num = [0, 1-1.6+0.63]' As far as I understand, this shouldn't be a problem though. I removed the 0 because scipy.lfilter cannot handle when a[0] == 0, which corresponds to num[0] == [0] since the numerator is used in the denominator to determine M^{-1}.

### CODE REVIEW

**Comment by rssalessio** [comment]
I'm not sure tbh of this one. Lfilter is not used to perform deconvolution. If you check utils.py there is already a deconvolution function from scipy that I tried to use, but somehow has poorer performance in comparison to the deconvolution function I implemented.

**Comment by rssalessio** [comment]
https://github.com/rssalessio/PythonVRFT/blob/eb0461c67cab7deb2dc1b281cdb44857002c849a/vrft/utils.py#L123

**Comment by rssalessio** [comment]
Also deconvolve in scipy uses lfilter https://github.com/scipy/scipy/blob/5e9eb0102a32da2a4e25df346b5aa08aaaffc6cc/scipy/signal/signaltools.py#L2123
The problem is that I discovered it was not quite precise, in the unittest I had to set a quite large error threshold. Can you perhaps do more testing?

**Comment by alexberndt** [comment]
Sure, I can look at that. There is an alternative function to lfilter called sosfilt (https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.sosfilt.html) which is apparently more precise (numerically) than lfilter. I might change to that instead.

I'll update, and send you a new pull request then.

**Pull request closed without merging**
